apiVersion: apps/v1
kind: Deployment
metadata:
    name: comments
spec:
    selector:
        matchLabels:
            app: comments
    template:
        metadata:
            labels:
                app: comments
        spec:
            containers:
                - name: comments
                  image: abdulovdb/k8s-comments
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: comments
spec:
    selector:
        app: comments
    ports:
        - port: 80
          targetPort: 4003
