apiVersion: apps/v1
kind: Deployment
metadata:
    name: posts
spec:
    selector:
        matchLabels:
            app: posts
    template:
        metadata:
            labels:
                app: posts
        spec:
            containers:
                - name: posts
                  image: abdulovdb/k8s-posts
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: posts
spec:
    selector:
        app: posts
    ports:
        - port: 80
          targetPort: 4002
