apiVersion: apps/v1
kind: Deployment
metadata:
    name: users
spec:
    selector:
        matchLabels:
            app: users
    template:
        metadata:
            labels:
                app: users
        spec:
            containers:
                - name: users
                  image: abdulovdb/k8s-users
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: users
spec:
    selector:
        app: users
    ports:
        - port: 80
          targetPort: 4001
    type: LoadBalancer
